CREATE TABLE "GAB_4743_ADDENDAXML" (
 "VENDOR_NUM" CHAR(6),
 "INVOICE_NUM" CHAR(50), 
"ADD_XML" LONGVARCHAR);
CREATE UNIQUE INDEX "GAB_4743_INVOICEK00" ON "GAB_4743_ADDENDAXML" ( "VENDOR_NUM", "INVOICE_NUM" );


CREATE TABLE "GAB_4743_GLXML"(
 "GL_NUMBER" CHAR(15),
 "POST_DATE" CHAR(8),
 "BATCH" CHAR(5),
 "LINE" NUMERIC(5,0),
 "DESCRIPTION" CHAR(30),
 "XML" LONGVARCHAR);

CREATE UNIQUE INDEX "ID_XML" ON "GAB_4743_GLXML"("GL_NUMBER", "BATCH", "LINE");